version: 2.1

orbs:
  windows: circleci/windows@2.4.0

jobs:
  install:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - run:
          name: "Display environment information"
          command: npx envinfo
      - run:
          name: "Install library dependencies with Yarn"
          command: yarn install --frozen-lockfile
      - run:
          name: "Restore NuGet packages for Components"
          command: nuget restore .\windows\ReactNativeNotes.sln
      - run:
          name: "Restore .NET dependencies"
          command: msbuild -t:restore .\windows\ReactNativeNotes.sln
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "windows/ReactNativeNotes.sln" }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - windows/packages

  verify:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "windows/ReactNativeNotes.sln" }}-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: "Verify the standards and code quality"
          command: npx eslint ./src/**
      - run:
          name: "Check the TypeScript code quality"
          command: yarn tsc --pretty

  # Application build
  build-Application-Configuration-Platform:
    parameters:
      configuration:
        type: enum
        enum: ["debug", "release"]
      platform:      
        type: enum
        enum: ["ARM64", "x64", "ARM", "Win32"]
    executor: windows/default
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "windows/ReactNativeNotes.sln" }}
            - v1-deps-
      - run:
          name: "Build the application for Windows OS"
          command: npx react-native run-windows --arch << parameters.platform >> --no-deploy --no-launch --no-packager --no-autolink --logging -- << parameters.configuration >>


workflows:
  version: 2.1
  build-x64:
    jobs:
      - install
      - verify:
          requires:
            - install
      - build-Application-Configuration-Platform:
          name: build-Application-Release-x64
          configuration: "release"
          platform: "x64"
          requires:
            - install
      - build-Application-Configuration-Platform:
          name: build-Application-Debug-x64
          configuration: "debug"
          platform: "x64"
          requires:
            - install
